create table observatorio (obs_identificador varchar(50),obs_nombre varchar(100),obs_direccion varchar(200));
alter table observatorio add primary key(obs_identificador);
create table volcan(obs_identificador varchar(50), vol_nombre varchar(100), vol_latitud float, vol_longitud float, vol_altitud float);
alter table volcan add primary key(vol_nombre);
alter table volcan add foreign key(obs_identificador) references observatorio(obs_identificador);
create table estacion_sismica(ess_codigo int, ess_s varchar(10),ess_c varchar(10), ess_n varchar(10), ess_l varchar(10));
alter table estacion_sismica add primary key(ess_codigo);
create table respuesta_estacionsismica(ess_codigo int, res_respuesta_z float,res_respuesta_n float,res_respuesta_e float);
alter table respuesta_estacionsismica add primary key(ess_codigo);
alter table respuesta_estacionsismica add foreign key(ess_codigo) references estacion_sismica(ess_codigo) DEFERRABLE INITIALLY DEFERRED;
alter table estacion_sismica add foreign key(ess_codigo) references respuesta_estacionsismica(ess_codigo) DEFERRABLE INITIALLY DEFERRED;
create table volcan_estacionsismica(vol_nombre varchar(100),ess_codigo int);
alter table volcan_estacionsismica add primary key(vol_nombre,ess_codigo);
alter table volcan_estacionsismica add foreign key(vol_nombre) references volcan(vol_nombre);
alter table volcan_estacionsismica add foreign key(ess_codigo) references estacion_sismica(ess_codigo);
create table sismo(sis_codigo int,vol_nombre varchar(100),  ess_codigo int,sis_tiempo_inicio timestamp,sis_amplitud float,sis_duracion float,sis_energia_liberada float);
alter table sismo add primary key (sis_codigo);
alter table sismo add foreign key(vol_nombre) references volcan(vol_nombre);
alter table sismo add foreign key(ess_codigo) references estacion_sismica(ess_codigo);
create table localizacion(loc_codigo int, sis_codigo int, loc_latitud float, loc_longitud float, loc_profundidad float,loc_tipo_localizacion varchar(100));
alter table localizacion add primary key(loc_codigo);
alter table localizacion add foreign key (sis_codigo) references sismo(sis_codigo);
create table estacion_so2(vol_nombre varchar(100),eso_identificador varchar(50),eso_latitud float, eso_longitud float, eso_altitud float,eso_tipo_estacion varchar(50));
alter table estacion_so2 add primary key(eso_identificador);
alter table estacion_so2 add foreign key(vol_nombre) references volcan (vol_nombre);
create table medida_so2(eso_identificador varchar(50), mso_flujo_so2 float, mso_hora_medida timestamp, mso_velocidad_viento float,mso_direccion_viento float);
alter table medida_so2 add primary key(eso_identificador,mso_hora_medida);
alter table medida_so2 add foreign key(eso_identificador) references estacion_so2(eso_identificador);
create table estacion_inclinometria(vol_nombre varchar(100),esi_identificador varchar(50),esi_latitud float, esi_logitud float, esi_altitud float);
alter table estacion_inclinometria add primary key(esi_identificador);
alter table estacion_inclinometria add foreign key(vol_nombre) references volcan(vol_nombre);
create table medida_inclinometro(esi_identificador varchar(50),min_codigo int,min_hora_medida timestamp, min_componentex float,min_componentey float,min_voltaje float,min_temperatura float);
alter table medida_inclinometro add primary key (min_codigo);
alter table medida_inclinometro add foreign key(esi_identificador) references estacion_inclinometria(esi_identificador);
create table cambio_tendencia_inclinometro(min_codigo int,cti_direccion varchar(100),cit_observacion varchar(1000));
alter table cambio_tendencia_inclinometro add primary key(min_codigo);
alter table cambio_tendencia_inclinometro add foreign key(min_codigo) references medida_inclinometro(min_codigo);